name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

#  charts_common:
#    path: ../charts_common/
  charts_common:
    git:
      url: https://github.com/SelfHealthNet/charts_common.git
      ref: 3ecc7fe10aea8fa3ba03d89569eb9de60065ffed
  collection: ^1.18.0
  intl: ^0.19.0
  logging: ^1.2.0
  meta: ^1.15.0

dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.13
#  flutter_test:
#    sdk: flutter
  test: ^1.25.8
